language: cpp 
os:
  - linux
  - osx
complier:
  - gcc 
addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake
      - doxygen
      - help2man
script:
  - g++ -g -Wall -Wextra -Werror anyoption.cpp demo.cpp -o demo
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./demo ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --error-exitcode=1 *.cpp *.h ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -q https://github.com/catchorg/Catch2/releases/download/v2.2.3/catch.hpp ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then g++ -g -o0 -std=c++11 -Wall -Wextra -Werror test.cpp anyoption.cpp -o test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./test ; fi


